project:
  type: website
  resources:
    - resumeWilliamMedwid.pdf

website:
  description: "A blog built with Quarto"
  site-url: https://williammedwid.com # you must change this appropriately for RSS feeds to work properly
  title: "Will's Stats Emporium"
  navbar:
    left:
      - text: Posts
        href: posts.qmd
    right:
      - icon: github
        href: https://github.com/GenghisKhandybar
      - icon: linkedin
        href: https://www.linkedin.com/in/william-medwid-8a5814178/
format:
  html:
    theme:
      - lux
      - brand
    css: styles.css

editor: visual

